- min

- max

- count

- mean

- mode

- medain

- variance

- standard deviation

- covariance

- correlation

- percentile

- quantile 

In [1]:
import numpy as np


In [2]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [ ]:
# take some list of values

# and try to get identify the methods 

# how many we are able to do

In [3]:
list1=[1,2,3,4,5,6]


**min**

In [4]:
np.min(list1)

1

In [5]:
arr1=np.array([[1,2,3],
              [10,20,30]])
arr1

array([[ 1,  2,  3],
       [10, 20, 30]])

In [6]:
arr1.shape

(2, 3)

In [7]:
np.min(arr1)

1

In [10]:
np.min(arr1,axis=1)

array([ 1, 10])

In [11]:
np.min(arr1,axis=0)

array([1, 2, 3])

- axis 0 indicates rows

- axis 1 indicates columns

**sum**

In [15]:
arr1=np.array([[50,150,22],
              [10,20,30]])
arr1

array([[ 50, 150,  22],
       [ 10,  20,  30]])

In [16]:
np.sum(arr1)

282

In [17]:
np.sum(arr1,axis=0)

array([ 60, 170,  52])

In [ ]:
[ 50, 150,  22]+[ 10,  20,  30]

In [19]:
np.sum(arr1,axis=1)
# [50,150,22]= 50+150+22
# [10,20,30]= 10+20+30

array([222,  60])

- sum axis level

- axis=1 means row level sum

    - individula summation of list

- axis=0 means column level sum

**mean-median**

In [20]:
list1=[1,22,23,45,57,89,121]
np.mean(list1)

51.142857142857146

In [21]:
np.sum(list1)/len(list1)

51.142857142857146

In [23]:
from functools import reduce
reduce(lambda summ,i: summ+i,list1)

358

In [24]:
summ=0
for i in list1:
    summ=summ+i
summ

358

In [31]:
list1=[1,22,23,45,57,89,121]
summ=0
[summ:=summ+i for i in list1][-1]

358

In [ ]:
summ=0
for i in list1:
    summ=summ+i
summ
##########################################
list1=[1,22,23,45,57,89,121]
summ=0
[summ:=summ+i for i in list1][-1]
############################################
from functools import reduce
reduce(lambda summ,i: summ+i,list1)
########################################
np.sum(list1)

In [34]:
x=[10,20,30,40,50]
y=[14,22,32,42,52]
np.cov(x,y)

array([[250. , 240. ],
       [240. , 230.8]])

In [42]:
# step-1: mean of x
# step-2: mean of y
# step-3: subtract xi-xbar   
# step-4: subtract yi-ybar  
# step-5: step3*step4   sum
# step-6: divide by n-1
x=[10,20,30,40,50]
y=[14,22,32,42,52]  
x_bar=np.mean(x)
y_bar=np.mean(y)
x_minus_xbar= [i-x_bar for i in x]
y_minus_ybar= [i-y_bar for i in y]
list1=[i*j for i,j in zip(x_minus_xbar,y_minus_ybar)]
list1
summ=0
[summ:=summ+i for i in list1][-1]
summ/(len(x)-1)

240.0

**variance**

In [2]:
x=[10,20,30,40,50]
import numpy as np
np.var(x)

200.0

<img class="XqHOTb IGEbUc" alt="S^2 = \frac{\sum (x_i - \bar{x})^2}{n - 1}" src="https://www.gstatic.com/education/formulas2/553212783/en/sample_variance.svg" role="img" data-csiid="d7JuZ42HLLed4-EP69DY2AM_16" data-atf="0">m

In [12]:
# step-1: means
#         sum of all numbers /total numbers
# step-2: xi-xmean
# step-3: sum of step-2
# step-4: step3/N-1

x=[10,20,30,40,50]
# ================step-1==============================
summ=0
add=[summ:=summ+i for i in x][-1]
x_mean=add/len(x)
print("mean of x:",x_mean)
#====================step-2=============================
list1=[i-x_mean for i in x]
list1
#===================step-3=================================
list2=[i*i for i in list1]
list2
#====================step-4: sum of list2====================
sum(list2)/len(list2)

mean of x: 30.0


200.0

In [18]:
np.sum(np.square(x-np.mean(x)))/len(x)

200.0

**Sd**

In [3]:
x=[10,20,30,40,50]
import numpy as np
np.std(x)

14.142135623730951

<img class="XqHOTb IGEbUc" alt="\sigma={\sqrt {\frac {\sum(x_{i}-{\mu})^{2}}{N}}}" src="https://www.gstatic.com/education/formulas2/553212783/en/population_standard_deviation.svg" role="img" data-csiid="k7VuZ9CdNNqZ4-EP7c-O-AI_10" data-atf="0">

In [19]:
x=[10,20,30,40,50]
# ================step-1==============================
summ=0
add=[summ:=summ+i for i in x][-1]
x_mean=add/len(x)
print("mean of x:",x_mean)
#====================step-2=============================
list1=[i-x_mean for i in x]
list1
#===================step-3=================================
list2=[i*i for i in list1]
list2
#====================step-4: sum of list2====================
val=sum(list2)/len(list2)
val**0.5

mean of x: 30.0


14.142135623730951

In [21]:
np.sqrt(np.sum(np.square(x-np.mean(x)))/len(x))

14.142135623730951

**correlation**

In [4]:
x=[10,20,30,40,50]
y=[14,22,32,42,52] 
np.corrcoef(x,y)

array([[1.        , 0.99913307],
       [0.99913307, 1.        ]])

In [26]:
x=[10,20,30,40,50]
y=[14,22,32,42,52]  
x_bar=np.mean(x)
y_bar=np.mean(y)
x_minus_xbar= [i-x_bar for i in x]
y_minus_ybar= [i-y_bar for i in y]
list1=[i*j for i,j in zip(x_minus_xbar,y_minus_ybar)]
summ=0
[summ:=summ+i for i in list1][-1]
cov_xy=summ/(len(x))
################################################
def sd(val):
    summ=0
    add=[summ:=summ+i for i in val][-1]
    x_mean=add/len(val)
    list1=[i-x_mean for i in val]
    list2=[i*i for i in list1]
    sdx=sum(list2)/len(list2)
    return(sdx**0.5)

sdx=sd(x)
sdy=sd(y)
print(sdx,sdy)

corr= cov_xy/(sdx*sdy)
corr

14.142135623730951 13.588230201170424


0.9991330730923518

**Euclidain distance**

- distance between two points

<img src="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/300px-Euclidean_distance_2d.svg.png" decoding="async" width="300" height="207" class="mw-file-element" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/450px-Euclidean_distance_2d.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/55/Euclidean_distance_2d.svg/600px-Euclidean_distance_2d.svg.png 2x" data-file-width="360" data-file-height="248">

In [28]:
p=(3,5)  # (x1,y1)
q=(8,10) # (x2,y2)
x1,y1=p[0],p[1]
x2,y2=q[0],q[1]
d1=q[0]-p[0]
d2=q[1]-p[1]
(d1**2+d2**2)**0.5

7.0710678118654755

In [33]:
# method-2:
# convert into numpy firts
a1=np.array(p)
a2=np.array(q)
np.sqrt(np.sum(np.square(a2-a1)))

7.0710678118654755

In [34]:
np.array([10,20,30])-np.array([1,2,3])

array([ 9, 18, 27])

**linear algebra**

- package name: numpy

- class name  : linalg

- method name : norm

In [39]:
from numpy.linalg import norm
from numpy import var,std,mean
import numpy as np
p=(3,5)  # (x1,y1)
q=(8,10) # (x2,y2)
a1=np.array(p)
a2=np.array(q)
np.linalg.norm(a1-a2)

7.0710678118654755

In [ ]:
## Assignment
l1=[(2,5),(3,7),(4,8)]
l2=(5,10)
# min distance between which points
# max distance between which points



**Find the roots**

In [40]:
#x^2-3x+2
coeff=[1,-3,2]
np.roots(coeff)

array([2., 1.])

In [ ]:
- np.faltten

- np.vstack

- np.dot

- np.full

- np.ones

- np.zeros