- **Numpy : Numerical python**

- It is a Module used for all math operations

- we already seen math package

- But **Numpy** is better than **math**

- with numpy we can do complex math operations

- we can represent numbers in different way

    - list of elements basic level

    - arrays is related to numpy package

    - tensors represent by tensorflow package

    - torch represent by pytorch

**create an array**

In [1]:
!pip install numpy  # its already available

In [2]:
import numpy as np

In [3]:
np.__version__  # double underscore

'1.26.4'

In [5]:
l1=[1,2,3,4]
arr1=np.array(l1)
arr1

array([1, 2, 3, 4])

In [6]:
type(l1)

list

In [7]:
type(arr1)
# ndarray === n dimensional array

numpy.ndarray

In [8]:
l1=[1,2,3,4]
l2=[10,20,30,40]
# [10,40,90,160]
[i*j for i,j in zip(l1,l2)]

[10, 40, 90, 160]

In [13]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,40,40])
arr1*arr2

array([ 10,  40, 120, 160])

In [14]:
arr2-arr1

array([ 9, 18, 37, 36])

In [15]:
arr2+arr1

array([11, 22, 43, 44])

In [17]:
arr1-arr2

array([ -9, -18, -37, -36])

In [19]:
op=arr1*arr2
list(op)

[10, 40, 120, 160]

In [20]:
op.tolist()

[10, 40, 120, 160]

In [21]:
arr2/arr1

array([10.        , 10.        , 13.33333333, 10.        ])

**NUMPY ALWAYS PERFORM ELEMENT WISE OPERATIONS**

**Use case-2**

- processing time is very very less using numpy compare to list

In [25]:
import time
l1=range(1,100000000)
l2=range(1,100000000)
start=time.time()
for i,j in zip(l1,l2):
    pass
end=time.time()
print("time taken:",end-start)

time taken: 9.237905979156494


In [27]:
l=range(1,10)
for i in l:
    print(i,end=' ')

1 2 3 4 5 6 7 8 9 

In [30]:
import time
l1=range(1,100000000)
l2=range(1,100000000)
start=time.time()
[i*j for i,j in zip(l1,l2)]
end=time.time()
print("time taken:",end-start)

time taken: 27.691827535629272


**arange**

- arange is same like range

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
import time
arr1=np.arange(1,100000000)
arr2=np.arange(1,100000000)
start=time.time()
arr1*arr2
end=time.time()
print("time taken:",end-start)

time taken: 0.23227787017822266
